spring:
  profiles:
    include:
#      - h2
      - postgre
      - oauth
#      - security

  main:
    allow-circular-references: true
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 457190401330-d0kdd9mkfr8gptk868o0a89oorlvrnre.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

logging:
  level:
    org:
      hibernate:
        type:
          sql: DEBUG
          descriptor:
            sql: DEBUG

sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: 457190401330-d0kdd9mkfr8gptk868o0a89oorlvrnre.apps.googleusercontent.com
      secret: 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
      callback:
        url: http://localhost:8080/auth/google/callback